"use client";
import Link from "next/link";
import Menu from "./Menu";
import "../styles/globals.css";

import { store } from "./store/store";
import { Provider } from "react-redux";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Menu />
          {children}
        </Provider>
      </body>
    </html>
  );
}
